In [ ]:
import pandas as pd 
import numpy as np

In [ ]:
data=pd.read_csv(r"C:\Users\vrish\Downloads\icu_mortality_train.csv ")

In [ ]:
data.head(10)

,RecordID,Age,Gender,Height,Weight,Urine,HR,Temp,NIDiasABP,SysABP,...,PaCO2,PaO2,Platelets,MAP,K,Na,FiO2,GCS,ICUType,In-hospital_death
0,137021.0,66.0,1.0,177.8,102.00,117.50,113.41,37.23,56.61,NaN,...,NaN,NaN,209.00,NaN,4.25,137.00,NaN,15.00,2.0,0
1,133611.0,50.0,1.0,NaN,92.40,210.51,85.93,38.04,58.60,126.69,...,41.00,175.00,243.33,88.02,4.38,144.00,0.51,6.88,4.0,0
2,137860.0,40.0,1.0,185.4,81.80,467.41,98.83,36.83,57.88,157.63,...,38.82,127.12,143.33,108.53,4.33,139.67,0.55,7.65,4.0,0
3,134781.0,58.0,1.0,180.3,99.22,86.55,81.63,36.96,49.64,113.86,...,46.20,147.60,109.60,78.06,4.07,137.75,0.58,13.50,2.0,0
4,133534.0,80.0,1.0,NaN,73.00,194.12,71.86,37.10,72.85,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.00,3.0,0
5,141457.0,90.0,0.0,NaN,NaN,73.62,73.63,36.93,55.17,NaN,...,NaN,NaN,371.00,NaN,4.10,137.00,NaN,11.95,3.0,0
6,135357.0,62.0,0.0,NaN,89.10,167.50,89.75,37.43,77.43,135.33,...,45.40,166.20,193.33,105.67,3.89,139.20,0.52,12.77,1.0,0
7,134112.0,58.0,1.0,NaN,NaN,105.00,89.90,36.92,78.32,NaN,...,NaN,NaN,554.50,NaN,4.05,136.50,NaN,15.00,1.0,0
8,133995.0,80.0,1.0,190.5,110.00,94.53,65.13,36.62,67.17,131.94,...,48.62,158.62,151.00,79.23,4.22,136.40,0.49,11.47,4.0,0
9,133120.0,76.0,0.0,NaN,NaN,385.00,77.13,36.61,64.49,NaN,...,NaN,NaN,149.00,NaN,3.80,141.00,NaN,15.00,1.0,0

In [ ]:
data.tail(10)

,RecordID,Age,Gender,Height,Weight,Urine,HR,Temp,NIDiasABP,SysABP,...,PaCO2,PaO2,Platelets,MAP,K,Na,FiO2,GCS,ICUType,In-hospital_death
3990,142582.0,60.0,1.0,167.6,53.55,144.58,107.08,37.36,55.07,106.87,...,46.00,217.33,225.25,75.66,4.15,138.00,0.58,13.33,1.0,0
3991,138022.0,73.0,1.0,NaN,108.31,60.85,95.33,36.08,50.14,NaN,...,45.50,97.00,68.00,NaN,6.31,131.60,0.39,14.77,3.0,0
3992,132688.0,71.0,0.0,162.6,104.00,149.38,96.56,37.07,42.00,106.33,...,37.81,122.94,147.43,74.00,4.43,138.00,0.49,12.81,2.0,0
3993,137577.0,80.0,0.0,152.4,71.00,44.92,107.98,36.69,50.10,100.14,...,38.87,136.93,136.50,74.91,4.64,139.50,0.61,6.00,4.0,1
3994,141422.0,77.0,1.0,167.6,73.46,82.29,91.00,37.43,49.14,117.88,...,46.71,174.36,83.25,72.74,4.65,139.25,0.48,10.58,2.0,0
3995,142287.0,41.0,1.0,NaN,142.00,129.00,86.35,37.48,62.74,126.59,...,43.00,122.00,386.00,102.64,4.07,138.00,0.40,13.71,4.0,0
3996,133064.0,50.0,1.0,NaN,69.91,297.22,81.81,36.99,63.82,NaN,...,NaN,NaN,245.67,NaN,4.00,137.33,NaN,15.00,3.0,1
3997,134121.0,65.0,0.0,NaN,104.91,158.37,103.81,36.99,64.58,148.16,...,47.20,123.33,265.33,96.68,4.36,144.60,0.60,4.31,3.0,0
3998,137994.0,27.0,0.0,NaN,84.40,30.56,106.41,35.37,59.09,126.50,...,20.47,170.42,195.83,93.40,3.31,130.00,0.39,3.46,3.0,1
3999,138658.0,64.0,0.0,152.4,78.68,75.00,87.84,36.82,NaN,113.66,...,35.08,136.92,328.33,81.61,4.43,135.50,0.52,12.15,2.0,0

In [7]:
data.isnull().sum

<bound method DataFrame.sum of       RecordID    Age  Gender  Height  Weight  Urine     HR   Temp  NIDiasABP  \
0        False  False   False   False   False  False  False  False      False
1        False  False   False    True   False  False  False  False      False
2        False  False   False   False   False  False  False  False      False
3        False  False   False   False   False  False  False  False      False
4        False  False   False    True   False  False  False  False      False
...        ...    ...     ...     ...     ...    ...    ...    ...        ...
3995     False  False   False    True   False  False  False  False      False
3996     False  False   False    True   False  False  False  False      False
3997     False  False   False    True   False  False  False  False      False
3998     False  False   False    True   False  False  False  False      False
3999     False  False   False   False   False  False  False  False       True

      SysABP  ...  PaCO2   PaO2  Platelets    MAP      K     Na   FiO2    GCS  \
0       True  ...   True   True      False   True  False  False   True  False
1      False  ...  False  False      False  False  False  False  False  False
2      False  ...  False  False      False  False  False  False  False  False
3      False  ...  False  False      False  False  False  False  False  False
4       True  ...   True   True       True   True   True   True   True  False
...      ...  ...    ...    ...        ...    ...    ...    ...    ...    ...
3995   False  ...  False  False      False  False  False  False  False  False
3996    True  ...   True   True      False   True  False  False   True  False
3997   False  ...  False  False      False  False  False  False  False  False
3998   False  ...  False  False      False  False  False  False  False  False
3999   False  ...  False  False      False  False  False  False  False  False

      ICUType  In-hospital_death
0       False              False
1       False              False
2       False              False
3       False              False
4       False              False
...       ...                ...
3995    False              False
3996    False              False
3997    False              False
3998    False              False
3999    False              False

[4000 rows x 22 columns]>

In [8]:
data.dropna(inplace=True)

In [9]:
data.isnull().sum

<bound method DataFrame.sum of       RecordID    Age  Gender  Height  Weight  Urine     HR   Temp  NIDiasABP  \
2        False  False   False   False   False  False  False  False      False
3        False  False   False   False   False  False  False  False      False
8        False  False   False   False   False  False  False  False      False
12       False  False   False   False   False  False  False  False      False
15       False  False   False   False   False  False  False  False      False
...        ...    ...     ...     ...     ...    ...    ...    ...        ...
3989     False  False   False   False   False  False  False  False      False
3990     False  False   False   False   False  False  False  False      False
3992     False  False   False   False   False  False  False  False      False
3993     False  False   False   False   False  False  False  False      False
3994     False  False   False   False   False  False  False  False      False

      SysABP  ...  PaCO2   PaO2  Platelets    MAP      K     Na   FiO2    GCS  \
2      False  ...  False  False      False  False  False  False  False  False
3      False  ...  False  False      False  False  False  False  False  False
8      False  ...  False  False      False  False  False  False  False  False
12     False  ...  False  False      False  False  False  False  False  False
15     False  ...  False  False      False  False  False  False  False  False
...      ...  ...    ...    ...        ...    ...    ...    ...    ...    ...
3989   False  ...  False  False      False  False  False  False  False  False
3990   False  ...  False  False      False  False  False  False  False  False
3992   False  ...  False  False      False  False  False  False  False  False
3993   False  ...  False  False      False  False  False  False  False  False
3994   False  ...  False  False      False  False  False  False  False  False

      ICUType  In-hospital_death
2       False              False
3       False              False
8       False              False
12      False              False
15      False              False
...       ...                ...
3989    False              False
3990    False              False
3992    False              False
3993    False              False
3994    False              False

[1116 rows x 22 columns]>

In [11]:
data.columns

Index(['RecordID', 'Age', 'Gender', 'Height', 'Weight', 'Urine', 'HR', 'Temp',
       'NIDiasABP', 'SysABP', 'DiasABP', 'pH', 'PaCO2', 'PaO2', 'Platelets',
       'MAP', 'K', 'Na', 'FiO2', 'GCS', 'ICUType', 'In-hospital_death'],
      dtype='str')

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [12]:
X = data.drop("In-hospital_death", axis=1)
y = data ["In-hospital_death"]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42)

In [16]:
model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

In [17]:
model.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, n_estimators=200, random_state=42)

In [18]:
y_pred = model.predict(X_test)

In [19]:
print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8928571428571429

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.99      0.94       199
           1       0.60      0.12      0.20        25

    accuracy                           0.89       224
   macro avg       0.75      0.55      0.57       224
weighted avg       0.87      0.89      0.86       224


Confusion Matrix:
[[197   2]
 [ 22   3]]

In [21]:
new_patient_1 = [[
10001,   # RecordID
45,      # Age
1,       # Gender (1=Male, 0=Female)
170,     # Height (cm)
72,      # Weight (kg)
1500,    # Urine (ml/day)
78,      # HR
36.8,    # temp
75,      # NIDiasABP
120,     # SysABP
80,      # DiasABP
7.40,    # pH
40,      # PaCO2
95,      # PaO2
250,     # Platelets
93,      # MAP
4.2,     # K
140,     # Na
0.21,    # FiO2 (room air)
15,      # GCS
2        # ICUType
]]

In [22]:
new_patient_1=pd.DataFrame(new_patient_1)

In [23]:
new_patient_1=pd.get_dummies(new_patient_1)

In [24]:
new_patient_1=new_patient_1.reindex(columns=X_train.columns,fill_value=0)

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
scaler = StandardScaler()

In [27]:
scaler.fit(X)

StandardScaler()

In [28]:
new_patient_1=scaler.transform(new_patient_1)

In [29]:
prediction=model.predict(new_patient_1)

C:\Users\vrish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [30]:
probability=model.predict_proba(new_patient_1)

C:\Users\vrish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [31]:
print(f"prediction risk level:{prediction[0]}")

prediction risk level:1

In [33]:
confidence=float(max(probability[0]))
print(f"model confidence :{confidence*100:2f}%")

model confidence :67.000000%